name: minerl2
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - py-opencv
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - pytorch-cuda=11.8
  - setuptools=65.0.0
  - black
  - coloredlogs
  - matplotlib
  - attrs
  - stable-baselines3==1.4.0
  - pip:
      - git+https://github.com/minerllabs/minerl
      - aicrowd-api
      - aicrowd-gym
      - gym3
      - tensorboard
